services:
  - type: web
    name: vela-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:socket_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: API_BASE_URL
        sync: false
